search:
  fields:
    query:
      required: true
      selector:
        text:
    anilist_id:
      required: false
      selector:
        number:
          min: 1
          mode: box

add_later:
  fields:
    anilist_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
